version: "3"

services:
  server:
    image: nginx
    container_name: server
    networks:
      - app_net
    volumes:
      - ./app/<template>/static:/srv/static
      - ./config/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    depends_on:
      - <template>
  <template>:
    image: <template>:latest
    build: 
      context: ./config
      dockerfile: <template>.Dockerfile
    working_dir: /var/app
    env_file: ./config/<template>.env
    container_name: <template>
    networks:
      - app_net
    volumes:
      - ./app/<template>:/var/app/
    command: ["gunicorn", "app:create_app()", "-c/var/gunicorn.conf.py"]

networks:
  app_net:

