events {}

http{

    # A list of mime types the server will accept
    # Using the built in mime types for the most common types
    # otherwise have to manually list:
    #   types { 
    #       text/plain;
    #       text/html;
    #       etc.. 
    #   }
    include mime.types;


    sendfile on;

    upstream app_server {
        server admin:3000;
    }

    server {

        listen 80;
        server_name localhost;

        location /static/ {
            root /srv/;
            autoindex on;
        }
        
        location = /favicon.ico { 
            access_log off; 
            log_not_found off; 
        }

        location / {
            proxy_pass http://app_server;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header Host $host;
            proxy_redirect off;
        }
    }
}